/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'surface-tint': '#6750a4',
        'on-primary': '#ffffff',
        'tertiary-fixed-dim': '#eeb8c8',
        'on-secondary-fixed-variant': '#4a4358',
        'inverse-primary': '#cfbcff',
        'tertiary-container': '#7d5260',
        'surface-container-lowest': '#ffffff',
        'surface-container-highest': '#e5e1e7',
        'on-tertiary-container': '#ffcbda',
        'secondary-fixed': '#e8def9',
        'on-surface-variant': '#494551',
        'on-error-container': '#93000a',
        'primary-fixed-dim': '#cfbcff',
        'on-secondary': '#ffffff',
        'surface-bright': '#fdf8fd',
        'on-tertiary-fixed': '#31111d',
        'inverse-surface': '#313034',
        'on-secondary-fixed': '#1e192b',
        'on-error': '#ffffff',
        'inverse-on-surface': '#f4eff5',
        'surface-container': '#f1ecf2',
        'primary-container': '#6750a4',
        'tertiary': '#633b48',
        'surface-variant': '#e5e1e7',
        'secondary-container': '#e8def9',
        'on-primary-fixed-variant': '#4f378a',
        'error-container': '#ffdad6',
        'tertiary-fixed': '#ffd9e3',
        'on-primary-container': '#e0d2ff',
        'on-surface': '#1c1b1f',
        'surface-container-low': '#f7f2f8',
        'surface-container-high': '#ebe7ec',
        'primary': '#7c3aed',
        'secondary-fixed-dim': '#ccc2dc',
        'on-tertiary': '#ffffff',
        'on-background': '#1c1b1f',
        'surface-dim': '#ddd9de',
        'secondary': '#625b71',
        'outline-variant': '#cbc4d2',
        'primary-fixed': '#e9ddff',
        'on-tertiary-fixed-variant': '#633b48',
        'surface': '#fdf8fd',
        'outline': '#7a7582',
        'on-secondary-container': '#686177',
        'on-primary-fixed': '#22005d',
        'background': '#fdf8fd',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        'margin-mobile': '16px',
        'margin-desktop': '32px',
        gutter: '24px',
      },
      backgroundImage: {
        'primary-gradient': 'linear-gradient(135deg, #d61b5f 0%, #7c3aed 50%, #d61b5f 100%)',
      },
      fontFamily: {
        'display-lg': ['Plus Jakarta Sans'],
        'headline-lg': ['Plus Jakarta Sans'],
        'title-lg': ['Plus Jakarta Sans'],
        'body-lg': ['Plus Jakarta Sans'],
        'body-md': ['Plus Jakarta Sans'],
        'label-lg': ['Plus Jakarta Sans'],
        'label-md': ['Plus Jakarta Sans'],
      },
      fontSize: {
        'display-lg': ['57px', { lineHeight: '64px', letterSpacing: '-0.25px', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '600' }],
        'title-lg': ['22px', { lineHeight: '28px', fontWeight: '500' }],
        'body-lg': ['16px', { lineHeight: '24px', letterSpacing: '0.5px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', letterSpacing: '0.25px', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.1px', fontWeight: '500' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.5px', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
}
